### PR TITLE
updates to the changelog

### PR DESCRIPTION
**Pull request by ronnaf**
- update article thumbnails (window inside, gradient box outside)
- add popup menu when hovering on "solution" on header

image
Page 2 - June Changelog 2-16-2022 10-58-45 PM

### CODE REVIEW

**Comment by ferrucc-io** [comment]
we can remove the article thumbnails from here, let's just load an image like on master

**Comment by ronnaf** [comment]
updated!

image

**Comment by ronnaf** [comment]
i kinda zoomed in the images so they would have consistent border radius, hope that's ok

**Comment by ronnaf** [comment]
image

**Comment by ferrucc-io** [comment]
lgtm

**Pull request merged**
